export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_LOADER="HIDE_LOADER";
export const CHECK_PERMISSION="CHECK_PERMISSION";
export const SHOW_POPUP = "SHOW_POPUP";
export const HIDE_POPUP = "HIDE_POPUP";